language: python
cache: pip
notifications:
  email: false
python:
  - "3.5"
  - "3.6"
os:
  - linux
# command to install dependencies
install:
  - pip install numpy
  - travis_wait pip install --no-binary pymatgen
  - travis_wait pip install .
# command to run tests
script:
  - python -m unittest discover tests
